---
badbehavior: 
  version: 0.0.0
  required: false
  description: '<a href="http://www.bad-behavior.ioerror.us/">Bad Behavior</a> analyzes how people are using the site in order to try to prevent spammers from posting.'
  license: 
    name: LGPL
    description: Licensed under the GNU LESSER GENERAL PUBLIC LICENSE.
    url: http://www.gnu.org/copyleft/lesser.html 
  homeable: false
  tables: 
    badbehavior: |
      
      `id` I4 AUTO PRIMARY,
      `ip` C(15) NOT NULL,
      `date` I4 NOT NULL default 0,
      `request_method` X NOT NULL,
      `request_uri` X NOT NULL,
      `server_protocol` X NOT NULL,
      `http_headers` X NOT NULL,
      `user_agent` X NOT NULL,
      `request_entity` X NOT NULL,
      `key` X NOT NULL
      
  permissions: 
    p_badbehavior_admin: 
      description: Can admin bad behavior
      level: admin
